
# token types
LEFT_ASSOCIATIVE, RIGHT_ASSOCIATIVE = +1, -1 # Left to right, Right to left
VALUE, CALLED_VALUE, INFIX, CONTINUING_INFIX, PREFIX, CALLED_PREFIX, POSTFIX, CONTINUING_POSTFIX, SEPERATOR, END_GROUP = 0,1,2,3,4,5,6,7,8,9